<?php

namespace app\index\controller;

use app\BaseController;
use app\model\Ad;
use app\model\Article;
use app\model\Content;
use app\model\Tags;
use think\facade\Session;
use think\facade\View;
use think\Request;

//qq571031767  微博：@沙坪坝韩宇
class Index extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {

        $banner = Ad::where("board_id",7)->limit(6)->select();
        View::assign("banner",$banner);

        //头条调取1条
        $headline = Content::where("status",1)
            ->where("tags","=","头条")
            ->order("id DESC")
            ->limit(1)
            ->find();
        View::assign("headline",$headline);

        //快手教程 21
        $ksjc = Content::where("cate_id",21)->order("id DESC")->find();
        View::assign("ksjc",$ksjc);




        $list = Article::cache(1)->where(1)->order("id DESC")->paginate();
        View::assign("list",$list);
        View::assign("title","首页");
        return view();
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read(Request $id)
    {
        //
        p($id);
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
