<?php

namespace app\index\controller;

use app\BaseController;
use think\facade\Session;

//qq571031767  微博：@沙坪坝韩宇
class Logged extends BaseController
{
    public function initialize()
    {
        $index_user = Session::get("index_user");
        if(is_null($index_user)){
            $this->redirect(url("index/login/index"));
        }
        parent::initialize(); // TODO: Change the autogenerated stub

    }
    public function redirect($url){
        if(!$url){
            $url = url("index/index/index");
        }
        header("Location:{$url}");
//确保重定向后，后续代码不会被执行
        exit;
    }


}
