<?php

namespace app\index\controller;

use app\BaseController;

use app\model\User;

use think\facade\Session;
use think\Request;
use think\exception\ValidateException;
//qq571031767  微博：@沙坪坝韩宇
class Login extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        return view();
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        $data = \think\facade\Request::post();
        try {
            $result = validate(\app\validate\Login::class)->check($data);

            if (true !== $result) {
                // 验证失败 输出错误信息
                $return["code"] = 201;
                //$return["msg"] = $result;
                $return["msg"] = "数据格式错误";
                return json($return);
            }
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            $return["code"] = 201;
            $return["msg"] = $e->getError();
            //$return["msg"] = "数据不能为空";
            return json($return);
        }



        $username = $data["username"];
        $res = User::where("username",$username)
            ->whereOr("phone",$username)
            ->whereOr("email",$username)
            ->find();
        if($res->password != md5($data["password"])){
            $return["code"] = 204;
            $return["msg"] = "密码错误";
            return json($return);
        }
        $user = $res->toArray();
        Session::set("index_user",$user);
        $return["code"] = 200;
        $return["msg"] = "成功";
        return json($return);

    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read(Request $id)
    {
        //
        p($id);
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
