<?php

namespace app\index\controller;

use app\BaseController;
use think\facade\View;
use think\Request;

//qq571031767  微博：@沙坪坝韩宇
class Search extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $keyword = \think\facade\Request::param("keyword");
        if(!$keyword){
            $map = 1;
        }else{
            $map = "`title` like '%".$keyword."%'";
        }

        $list = \app\model\Content::where($map)
            ->where("status",1)
            ->order("id DESC")
            ->select();
        View::assign("list",$list);
        View::assign("keyword",$keyword);
        View::assign("title","首页");
        return view();
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        $content = \app\model\Content::with("model")->find($id);

        switch ($content["model"]["model_name"]){
            case "Article":
                $res = \app\model\Article::find($id);
                $view = "article";
            case "Video";
                $res = \app\model\Video::find($id);
                $view = "video";
            case "Thumb";
                $res = \app\model\Thumb::find($id);
                $view = "thumb";
            case "Soft";
                $res = \app\model\Soft::find($id);
                $view = "soft";
            default:
                $res = \app\model\Article::find($id);
                $view = "article";
        }
        View::assign("res",$res);
        View::assign("content",$content);
        return View::fetch($view);
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
