<?php

namespace app\admin\controller;

use app\model\Content;
use think\facade\Session;
use think\facade\View;
use think\Request;
use think\exception\ValidateException;
//qq571031767  微博：@沙坪坝韩宇
class Cache extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function clear()
    {
        //分类显示
       $res = \think\facade\Cache::clear();
        if($res){
            return json(["code"=>200,"msg"=>"成功"]);
        }else{
            return json(["code"=>204,"msg"=>"请稍后再试"]);
        }
    }


}
