<?php

namespace app\admin\controller;

use app\BaseController;
use think\facade\Session;

//qq571031767  微博：@沙坪坝韩宇
class Common extends BaseController
{
    public function initialize()
    {

        $admin_user = Session::get("admin_user");

        if(is_null($admin_user)){
            $index_user = Session::get("index_user");
            if($index_user["is_admin"] == 0){
                die("用户权限不足");
            }else{
                Session::set("admin_user",$index_user);
            }
        }
        parent::initialize(); // TODO: Change the autogenerated stub

    }
    public function redirect($url){
        if(!$url){
            $url = url("index/index/index");
        }
        header("Location:{$url}");
//确保重定向后，后续代码不会被执行
        exit;
    }


}
