<?php

namespace app\admin\controller;

use app\model\Content;
use think\facade\Session;
use think\facade\View;
use think\Request;
use think\exception\ValidateException;
//qq571031767  微博：@沙坪坝韩宇
class Comment extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }





    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $id = \think\facade\Request::param("id");
        $title = \think\facade\Request::param("title");
        $status = \think\facade\Request::param("status");
        if($id){
            $map["id"] = $id;
        }
        if($title){
            if(isset($map)){
                unset($map);
            }
            $map= [
                ['title', 'like', "%{$title}%"],
            ];
        }
        if($status){
            $map["status"] = $status;
        }
        if(!isset($map)){
            $map=1;
        }

        $list = \app\model\Comment::with(["cont","user"])
            ->where($map)
            ->order("status DESC ,id DESC")
            ->paginate();
        View::assign("list",$list);
        View::assign("title","文章列表");
        return view();
    }



    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        $res = \app\model\Comment::where("id",$id)->delete();
        if($res){
            return json(["code"=>200,"msg"=>"成功"]);
        }else{
            return json(["code"=>204,"msg"=>"稍后再试"]);
        }
    }

    //通过审核
    public function pass_comment($id)
    {
        $res = \app\model\Comment::where("id",$id)->save(["status"=>1]);
        if($res){
            return json(["code"=>200,"msg"=>"成功"]);
        }else{
            return json(["code"=>204,"msg"=>"稍后再试"]);
        }
    }
}
